import type { Metadata } from "next";
import { Navbar } from "./_components";

export const metadata: Metadata = {
  title: "Cloud Project",
  description: "Generated by create next app",
};

const CloudLayout = ({ children }: { children: React.ReactNode }) => (
  <>
    <Navbar />
    {children}
  </>
);

export default CloudLayout;
