import type { Metadata } from "next";
import { Header } from "./_copmonents/index";

export const metadata: Metadata = {
  title: "LinksList Project",
  description: "Generated by create next app",
};

const LinksListLayout = ({ children }: { children: React.ReactNode }) => (
  <>
    <Header />
    <main>
      <div className="max-w-4xl mx-auto p-6">{children}</div>
    </main>
  </>
);

export default LinksListLayout;
