import type { Metadata } from "next";
import { AdminSidebar } from "../_copmonents/index";

export const metadata: Metadata = {
  title: "LinkList Project",
  description: "Generated by create next app",
};

const AdminLayout = ({ children }: { children: React.ReactNode }) => (
  <main className="bg-gray-100 md:flex min-h-screen linklist">
    <aside className="bg-white w-48 p-4 pt-6 shadow">
      <AdminSidebar />
    </aside>
    <div className="grow">{children}</div>
  </main>
);

export default AdminLayout;
